# kustom-webapp/overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: replicas.yaml

configMapGenerator:
- name: mykustom-map
  envs:
  - config.properties
